"""Creacion del perfil financiero DatosAsociado y enums

Revision ID: 209ca991c335
Revises: 28aae42978f1
Create Date: 2026-06-30 17:29:46.056980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '209ca991c335'
down_revision: Union[str, Sequence[str], None] = '28aae42978f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- EL FIX MANUAL PARA EL ENUM DE POSTGRES ---
    op.execute("CREATE TYPE tipocomentarioenum AS ENUM ('PERSONA', 'VOLUNTARIO', 'ASOCIADO', 'EXPEDIENTE')")
    op.create_table('derivacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivacion_nombre'), 'derivacion', ['nombre'], unique=True)
    op.create_table('motivo_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivo_consulta_nombre'), 'motivo_consulta', ['nombre'], unique=True)
    op.create_table('nivel_educativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nivel_educativo_nombre'), 'nivel_educativo', ['nombre'], unique=True)
    op.create_table('tecnica_acogida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnica_acogida_nombre'), 'tecnica_acogida', ['nombre'], unique=True)
    op.create_table('datos_asociado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('numero_registro_asociado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'BANCO', name='metodopagoenum'), nullable=False),
    sa.Column('autoriza_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('estado_membresia', sa.Enum('ACTIVO', 'INACTIVO', 'RENOVADO', name='estadoasociadoenum'), nullable=False),
    sa.Column('estado_pago', sa.Enum('AL_DIA', 'PENDIENTE', 'MOROSO', name='estadopagoenum'), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_index(op.f('ix_datos_asociado_numero_registro_asociado'), 'datos_asociado', ['numero_registro_asociado'], unique=True)
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_expediente_asignado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_tramite', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('fecha_presentacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('EN_TRAMITE', 'RESUELTO', 'DENEGADO', 'ARCHIVADO', name='estadoexpedienteenum'), nullable=False),
    sa.Column('representante_legal', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('consultorio_juridico', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('aporte_social', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('solicitante_extranjeria', sa.Boolean(), nullable=False),
    sa.Column('antecedentes_traducidos', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expediente_numero_registro'), 'expediente', ['numero_registro'], unique=True)
    op.create_table('telefono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datosasociado')
    op.add_column('comentario', sa.Column('tipo', sa.Enum('PERSONA', 'VOLUNTARIO', 'ASOCIADO', 'EXPEDIENTE', name='tipocomentarioenum'), nullable=False))
    op.add_column('comentario', sa.Column('id_expediente', sa.Integer(), nullable=True))
    op.alter_column('comentario', 'fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('comentario', 'id_persona',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'comentario', 'expediente', ['id_expediente'], ['id'])
    op.add_column('persona', sa.Column('numero_identificacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.execute("CREATE TYPE generoenum AS ENUM ('M', 'H', 'LGTBI+')")
    op.add_column('persona', sa.Column('genero', sa.Enum('M', 'H', 'LGTBI+', name='generoenum'), nullable=False))
    # op.add_column('persona', sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # op.add_column('persona', sa.Column('ciudad_residencia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ... (esto ya lo tienes arriba)
    op.add_column('persona', sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('persona', sa.Column('ciudad_residencia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    
    # --- AQUÍ EMPIEZA LO QUE PEGAS (Tus parches salva-vidas) ---
    op.execute("CREATE TYPE situacionadminenum AS ENUM ('REGULAR', 'IRREGULAR', 'TRAMITE')")
    op.add_column('persona', sa.Column('situacion_administrativa', sa.Enum('REGULAR', 'IRREGULAR', 'TRAMITE', name='situacionadminenum'), nullable=False))
    
    op.add_column('persona', sa.Column('unidad_familiar', sa.Integer(), nullable=True))
    
    op.execute("CREATE TYPE opcionnaenum AS ENUM ('SI', 'NO', 'NA')")
    op.add_column('persona', sa.Column('madre_soltera', sa.Enum('SI', 'NO', 'NA', name='opcionnaenum'), nullable=False))
    op.add_column('persona', sa.Column('violencia_genero', sa.Enum('SI', 'NO', 'NA', name='opcionnaenum'), nullable=False))
    
    op.execute("CREATE TYPE padronenum AS ENUM ('SI', 'NO', 'OTRO')")
    op.add_column('persona', sa.Column('tiene_padron', sa.Enum('SI', 'NO', 'OTRO', name='padronenum'), nullable=False))
    
    op.add_column('persona', sa.Column('fecha_padron', sa.Date(), nullable=True))
    # --- AQUÍ TERMINA LO QUE PEGAS ---

    # Y de aquí para abajo dejas tu archivo tal cual estaba:
    # op.add_column('persona', sa.Column('autoriza_uso_imagen', sa.Boolean(), nullable=False))
    # op.add_column('persona', sa.Column('contacto_emergencia_nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('persona', sa.Column('autoriza_uso_imagen', sa.Boolean(), nullable=False))
    op.add_column('persona', sa.Column('contacto_emergencia_nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('persona', sa.Column('contacto_emergencia_parentesco', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('persona', sa.Column('contacto_emergencia_telefono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('persona', sa.Column('id_nivel_educativo', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('id_motivo_consulta', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('id_derivacion', sa.Integer(), nullable=True))
    op.add_column('persona', sa.Column('id_tecnica_acogida', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_persona_numero_identificacion'), 'persona', ['numero_identificacion'], unique=True)
    op.create_foreign_key(None, 'persona', 'tecnica_acogida', ['id_tecnica_acogida'], ['id'])
    op.create_foreign_key(None, 'persona', 'nivel_educativo', ['id_nivel_educativo'], ['id'])
    op.create_foreign_key(None, 'persona', 'derivacion', ['id_derivacion'], ['id'])
    op.create_foreign_key(None, 'persona', 'motivo_consulta', ['id_motivo_consulta'], ['id'])
    op.drop_column('persona', 'imagen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('imagen', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_index(op.f('ix_persona_numero_identificacion'), table_name='persona')
    op.drop_column('persona', 'id_tecnica_acogida')
    op.drop_column('persona', 'id_derivacion')
    op.drop_column('persona', 'id_motivo_consulta')
    op.drop_column('persona', 'id_nivel_educativo')
    op.drop_column('persona', 'contacto_emergencia_telefono')
    op.drop_column('persona', 'contacto_emergencia_parentesco')
    op.drop_column('persona', 'contacto_emergencia_nombre')
    op.drop_column('persona', 'autoriza_uso_imagen')
    op.drop_column('persona', 'fecha_padron')
    op.drop_column('persona', 'tiene_padron')
    op.drop_column('persona', 'violencia_genero')
    op.drop_column('persona', 'madre_soltera')
    op.drop_column('persona', 'unidad_familiar')
    op.drop_column('persona', 'situacion_administrativa')
    op.drop_column('persona', 'ciudad_residencia')
    op.drop_column('persona', 'codigo_postal')
    op.drop_column('persona', 'genero')
    op.drop_column('persona', 'numero_identificacion')
    op.drop_constraint(None, 'comentario', type_='foreignkey')
    op.alter_column('comentario', 'id_persona',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comentario', 'fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('comentario', 'id_expediente')
    op.drop_column('comentario', 'tipo')
    op.create_table('datosasociado',
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tramites', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], name=op.f('datosasociado_id_persona_fkey')),
    sa.PrimaryKeyConstraint('id_persona', name=op.f('datosasociado_pkey'))
    )
    op.drop_table('telefono')
    op.drop_index(op.f('ix_expediente_numero_registro'), table_name='expediente')
    op.drop_table('expediente')
    op.drop_index(op.f('ix_datos_asociado_numero_registro_asociado'), table_name='datos_asociado')
    op.drop_table('datos_asociado')
    op.drop_index(op.f('ix_tecnica_acogida_nombre'), table_name='tecnica_acogida')
    op.drop_table('tecnica_acogida')
    op.drop_index(op.f('ix_nivel_educativo_nombre'), table_name='nivel_educativo')
    op.drop_table('nivel_educativo')
    op.drop_index(op.f('ix_motivo_consulta_nombre'), table_name='motivo_consulta')
    op.drop_table('motivo_consulta')
    op.drop_index(op.f('ix_derivacion_nombre'), table_name='derivacion')
    op.drop_table('derivacion')
    # ### end Alembic commands ###
