"""Inyeccion de datos del Excel: Telefonos, Catalogos y Persona

Revision ID: 28aae42978f1
Revises: 35911e199c5b
Create Date: 2026-06-28 17:07:57.973352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28aae42978f1'
down_revision: Union[str, Sequence[str], None] = '35911e199c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datoscontratado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datoscontratado',
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcion', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('horas_contratadas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_termino', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], name=op.f('datoscontratado_id_persona_fkey')),
    sa.PrimaryKeyConstraint('id_persona', name=op.f('datoscontratado_pkey'))
    )
    # ### end Alembic commands ###
