"""Creacion inicial de tablas

Revision ID: 35911e199c5b
Revises: 
Create Date: 2026-06-14 06:45:57.406216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35911e199c5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_nombre_estado'), 'estado', ['nombre_estado'], unique=True)
    op.create_table('nacionalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nacionalidad_pais'), 'nacionalidad', ['pais'], unique=True)
    op.create_table('tipodocumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipodocumento_tipo'), 'tipodocumento', ['tipo'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=True),
    sa.Column('id_nacionalidad', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proteccion_datos', sa.Boolean(), nullable=False),
    sa.Column('imagen', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_nacionalidad'], ['nacionalidad.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipodocumento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_correo'), 'persona', ['correo'], unique=True)
    op.create_table('citaatencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datosasociado',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('tramites', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('datoscontratado',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('funcion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('horas_contratadas', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('datosvoluntario',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('area_voluntariado', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('horas_disponibles', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('personaestado',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_estado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaestado')
    op.drop_table('datosvoluntario')
    op.drop_table('datoscontratado')
    op.drop_table('datosasociado')
    op.drop_table('comentario')
    op.drop_table('citaatencion')
    op.drop_index(op.f('ix_persona_correo'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipodocumento_tipo'), table_name='tipodocumento')
    op.drop_table('tipodocumento')
    op.drop_index(op.f('ix_nacionalidad_pais'), table_name='nacionalidad')
    op.drop_table('nacionalidad')
    op.drop_index(op.f('ix_estado_nombre_estado'), table_name='estado')
    op.drop_table('estado')
    # ### end Alembic commands ###
