"""Refactor_Expedientes_y_AporteSocial

Revision ID: 453434791ead
Revises: 519f55ac8ce0
Create Date: 2026-07-07 22:30:47.019762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453434791ead'
down_revision: Union[str, Sequence[str], None] = '519f55ac8ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Añadir columna con un default en False para evitar errores de nullabilidad
    op.add_column('expediente', sa.Column('antecedentes_traducidos_y_apostillados', sa.Boolean(), nullable=True))
    op.execute('UPDATE expediente SET antecedentes_traducidos_y_apostillados = antecedentes_traducidos')
    op.alter_column('expediente', 'antecedentes_traducidos_y_apostillados', nullable=False)

    # Crear el tipo Enum en Postgres y hacer el casting explícito
    op.execute("CREATE TYPE aportesocialenum AS ENUM ('Sí', 'No', 'Subvencionado')")
    op.execute("ALTER TABLE expediente ALTER COLUMN aporte_social TYPE aportesocialenum USING aporte_social::aportesocialenum")
    
    op.drop_column('expediente', 'antecedentes_traducidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expediente', sa.Column('antecedentes_traducidos', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('UPDATE expediente SET antecedentes_traducidos = antecedentes_traducidos_y_apostillados')
    op.alter_column('expediente', 'antecedentes_traducidos', nullable=False)
    
    op.execute('ALTER TABLE expediente ALTER COLUMN aporte_social TYPE varchar(100)')
    op.execute('DROP TYPE aportesocialenum')
    
    op.drop_column('expediente', 'antecedentes_traducidos_y_apostillados')
    # ### end Alembic commands ###
