"""eliminar_citas

Revision ID: 519f55ac8ce0
Revises: b6e7df0b60c3
Create Date: 2026-07-07 16:47:07.647772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519f55ac8ce0'
down_revision: Union[str, Sequence[str], None] = 'b6e7df0b60c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citaatencion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citaatencion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], name=op.f('citaatencion_id_persona_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('citaatencion_pkey'))
    )
    # ### end Alembic commands ###
