"""migracion_inicial_limpia

Revision ID: 7b7122f89a54
Revises: 
Create Date: 2026-07-06 05:40:56.059792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b7122f89a54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivacion_nombre'), 'derivacion', ['nombre'], unique=True)
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_nombre_estado'), 'estado', ['nombre_estado'], unique=True)
    op.create_table('motivo_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivo_consulta_nombre'), 'motivo_consulta', ['nombre'], unique=True)
    op.create_table('nacionalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nacionalidad_pais'), 'nacionalidad', ['pais'], unique=True)
    op.create_table('nivel_educativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nivel_educativo_nombre'), 'nivel_educativo', ['nombre'], unique=True)
    op.create_table('tecnica_acogida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnica_acogida_nombre'), 'tecnica_acogida', ['nombre'], unique=True)
    op.create_table('tipodocumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipodocumento_tipo'), 'tipodocumento', ['tipo'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proteccion_datos', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('numero_identificacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('genero', sa.Enum('M', 'H', 'LGTBI', name='generoenum'), nullable=False),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ciudad_residencia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('situacion_administrativa', sa.Enum('REGULAR', 'IRREGULAR', 'TRAMITE', name='situacionadminenum'), nullable=False),
    sa.Column('unidad_familiar', sa.Integer(), nullable=True),
    sa.Column('madre_soltera', sa.Enum('SI', 'NO', 'NA', name='opcionnaenum'), nullable=False),
    sa.Column('violencia_genero', sa.Enum('SI', 'NO', 'NA', name='opcionnaenum'), nullable=False),
    sa.Column('tiene_padron', sa.Enum('SI', 'NO', 'OTRO', name='padronenum'), nullable=False),
    sa.Column('fecha_padron', sa.Date(), nullable=True),
    sa.Column('autoriza_uso_imagen', sa.Boolean(), nullable=False),
    sa.Column('contacto_emergencia_nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('contacto_emergencia_parentesco', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('contacto_emergencia_telefono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=True),
    sa.Column('id_nacionalidad', sa.Integer(), nullable=True),
    sa.Column('id_nivel_educativo', sa.Integer(), nullable=True),
    sa.Column('id_motivo_consulta', sa.Integer(), nullable=True),
    sa.Column('id_derivacion', sa.Integer(), nullable=True),
    sa.Column('id_tecnica_acogida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_derivacion'], ['derivacion.id'], ),
    sa.ForeignKeyConstraint(['id_motivo_consulta'], ['motivo_consulta.id'], ),
    sa.ForeignKeyConstraint(['id_nacionalidad'], ['nacionalidad.id'], ),
    sa.ForeignKeyConstraint(['id_nivel_educativo'], ['nivel_educativo.id'], ),
    sa.ForeignKeyConstraint(['id_tecnica_acogida'], ['tecnica_acogida.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipodocumento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_correo'), 'persona', ['correo'], unique=True)
    op.create_index(op.f('ix_persona_numero_identificacion'), 'persona', ['numero_identificacion'], unique=True)
    op.create_table('citaatencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datos_asociado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('numero_registro_asociado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'BANCO', name='metodopagoenum'), nullable=False),
    sa.Column('autoriza_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('estado_membresia', sa.Enum('ACTIVO', 'INACTIVO', 'RENOVADO', name='estadoasociadoenum'), nullable=False),
    sa.Column('estado_pago', sa.Enum('AL_DIA', 'PENDIENTE', 'MOROSO', name='estadopagoenum'), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_index(op.f('ix_datos_asociado_numero_registro_asociado'), 'datos_asociado', ['numero_registro_asociado'], unique=True)
    op.create_table('datos_voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('area_voluntariado', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('horas_disponibles', sa.Integer(), nullable=False),
    sa.Column('carta_compromiso_entregada', sa.Boolean(), nullable=False),
    sa.Column('formulario_inscripcion_entregado', sa.Boolean(), nullable=False),
    sa.Column('curriculum_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_expediente_asignado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_tramite', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('fecha_presentacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('EN_TRAMITE', 'RESUELTO', 'DENEGADO', 'ARCHIVADO', name='estadoexpedienteenum'), nullable=False),
    sa.Column('representante_legal', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('consultorio_juridico', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('aporte_social', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('solicitante_extranjeria', sa.Boolean(), nullable=False),
    sa.Column('antecedentes_traducidos', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expediente_numero_registro'), 'expediente', ['numero_registro'], unique=True)
    op.create_table('personaestado',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_estado')
    )
    op.create_table('telefono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('PERSONA', 'VOLUNTARIO', 'ASOCIADO', 'EXPEDIENTE', name='tipocomentarioenum'), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_expediente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_expediente'], ['expediente.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('telefono')
    op.drop_table('personaestado')
    op.drop_index(op.f('ix_expediente_numero_registro'), table_name='expediente')
    op.drop_table('expediente')
    op.drop_table('datos_voluntario')
    op.drop_index(op.f('ix_datos_asociado_numero_registro_asociado'), table_name='datos_asociado')
    op.drop_table('datos_asociado')
    op.drop_table('citaatencion')
    op.drop_index(op.f('ix_persona_numero_identificacion'), table_name='persona')
    op.drop_index(op.f('ix_persona_correo'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipodocumento_tipo'), table_name='tipodocumento')
    op.drop_table('tipodocumento')
    op.drop_index(op.f('ix_tecnica_acogida_nombre'), table_name='tecnica_acogida')
    op.drop_table('tecnica_acogida')
    op.drop_index(op.f('ix_nivel_educativo_nombre'), table_name='nivel_educativo')
    op.drop_table('nivel_educativo')
    op.drop_index(op.f('ix_nacionalidad_pais'), table_name='nacionalidad')
    op.drop_table('nacionalidad')
    op.drop_index(op.f('ix_motivo_consulta_nombre'), table_name='motivo_consulta')
    op.drop_table('motivo_consulta')
    op.drop_index(op.f('ix_estado_nombre_estado'), table_name='estado')
    op.drop_table('estado')
    op.drop_index(op.f('ix_derivacion_nombre'), table_name='derivacion')
    op.drop_table('derivacion')
    # ### end Alembic commands ###
