"""asociados_comentarios

Revision ID: b6e7df0b60c3
Revises: c83dff5b9cbb
Create Date: 2026-07-07 16:35:13.634540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6e7df0b60c3'
down_revision: Union[str, Sequence[str], None] = 'c83dff5b9cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos_asociado', sa.Column('comentarios', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datos_asociado', 'comentarios')
    # ### end Alembic commands ###
