"""crud_voluntarios

Revision ID: c83dff5b9cbb
Revises: 7b7122f89a54
Create Date: 2026-07-06 13:15:28.479770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c83dff5b9cbb'
down_revision: Union[str, Sequence[str], None] = '7b7122f89a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos_voluntario', sa.Column('campo_accion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False))
    op.add_column('datos_voluntario', sa.Column('tipo_voluntariado', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('datos_voluntario', sa.Column('copia_documento_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('datos_voluntario', 'area_voluntariado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos_voluntario', sa.Column('area_voluntariado', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('datos_voluntario', 'copia_documento_url')
    op.drop_column('datos_voluntario', 'tipo_voluntariado')
    op.drop_column('datos_voluntario', 'campo_accion')
    # ### end Alembic commands ###
