"""Creacion tabla voluntarios

Revision ID: f2d2ef87acf6
Revises: 209ca991c335
Create Date: 2026-06-30 18:18:40.141101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2d2ef87acf6'
down_revision: Union[str, Sequence[str], None] = '209ca991c335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('area_voluntariado', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('horas_disponibles', sa.Integer(), nullable=False),
    sa.Column('carta_compromiso_entregada', sa.Boolean(), nullable=False),
    sa.Column('formulario_inscripcion_entregado', sa.Boolean(), nullable=False),
    sa.Column('curriculum_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_persona')
    )
    op.drop_table('datosvoluntario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datosvoluntario',
    sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_voluntariado', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('horas_disponibles', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_termino', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], name=op.f('datosvoluntario_id_persona_fkey')),
    sa.PrimaryKeyConstraint('id_persona', name=op.f('datosvoluntario_pkey'))
    )
    op.drop_table('datos_voluntario')
    # ### end Alembic commands ###
